In [1]:
import numpy as np


In [2]:
## Arithmetic operation 

In [3]:
arr = np.arange(0,25)

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [5]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [7]:
arr**3

array([    0,     1,     8,    27,    64,   125,   216,   343,   512,
         729,  1000,  1331,  1728,  2197,  2744,  3375,  4096,  4913,
        5832,  6859,  8000,  9261, 10648, 12167, 13824])

In [8]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [9]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10])

In [10]:
np.max(arr)

24

In [11]:
## matrix opreation

In [13]:
x = np.array([[1,2],
            [4, 8]])
y = np.array([[5, 7],
            [2, 9]])


print ("sum:\n", x + y)


sum:
 [[ 6  9]
 [ 6 17]]


In [14]:
print ("multiplication:\n", x*y)

multiplication:
 [[ 5 14]
 [ 8 72]]


In [16]:
print ("multiply:\n", x.dot(y))

multiply:
 [[  9  25]
 [ 36 100]]


In [ ]:
# Trigonometric functions


In [18]:
import cmath
x=np.array([9,4,6,4])
print(x)
print(np.sin(x))
print(np.cos(x))

[9 4 6 4]
[ 0.41211849 -0.7568025  -0.2794155  -0.7568025 ]
[-0.91113026 -0.65364362  0.96017029 -0.65364362]


In [17]:
y=np.array([0.2,0.8,0.7,0.5])
print(y)
print(np.arccos(y))
print(np.arcsin(y))
print(np.arctan(y))

[0.2 0.8 0.7 0.5]
[1.36943841 0.64350111 0.79539883 1.04719755]
[0.20135792 0.92729522 0.7753975  0.52359878]
[0.19739556 0.67474094 0.61072596 0.46364761]
